### ISSUE TITLE
Error: spawn Unknown system error -86

### ISSUE THREAD

**Issue by jcs090218** [lem-project/setup-lem#8]
There is an error in the CI (https://github.com/lem-project/setup-lem/actions/runs/5238605627/jobs/9457658909#step:3:119):

```
/Users/runner/lem-v2.0.0/lem.app/Contents/MacOS/lem --version
node:internal/errors:465
    ErrorCaptureStackTrace(err);
    ^

Error: spawn Unknown system error -86
    at ChildProcess.spawn (node:internal/child_process:413:11)
    at Object.spawn (node:child_process:700:9)
    at ToolRunner.<anonymous> (/Users/runner/work/setup-lem/setup-lem/dist/index.js:1428:34)
    at Generator.next (<anonymous>)
    at /Users/runner/work/setup-lem/setup-lem/dist/index.js:1042:71
    at new Promise (<anonymous>)
    at __webpack_modules__.159.__awaiter (/Users/runner/work/setup-lem/setup-lem/dist/index.js:1038:12)
    at /Users/runner/work/setup-lem/setup-lem/dist/index.js:1410:53
    at new Promise (<anonymous>)
    at ToolRunner.<anonymous> (/Users/runner/work/setup-lem/setup-lem/dist/index.js:1410:20) {
  errno: -86,
  code: 'Unknown system error -86',
  syscall: 'spawn'
}
```

Reference https://github.com/puppeteer/puppeteer/issues/9142#issuecomment-1288461160.

What's the CPU architecture in macOS? 🤔 

cc @cxxxr

**Comment by cxxxr** [comment]
> What's the CPU architecture in macOS? 🤔

I assume apple silicon.

**Comment by jcs090218** [comment]
> I assume apple silicon.

That make sense since GHA uses x86. Do you plan to support different architectures? 🤔

**Comment by cxxxr** [comment]
Yes, I would like to include an intel version in the next release!

**Comment by jcs090218** [comment]
Awesome! Thank you! ;)
